spring:
  application:
    name: bookjeok-service

  config:
    activate:
      on-profile: local

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_LOCAL_DATASOURCE_URL}
    username: ${SPRING_LOCAL_DATASOURCE_USERNAME}
    password: ${SPRING_LOCAL_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.jamjam.bookjeok.domains

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

server:
  port: ${SERVER_PORT}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

tosspayments:
  wiget-secret-key: ${WIDGET_SECRET_KEY}
  api-secret-key: ${API_SECRET_KEY}

naver:
  book-client-api: ${BOOK_CLIENT_ID}
  book-secret-key: ${BOOK_CLIENT_KEY}

image:
  image-dir: ${IMAGE-DIRECTORY}
  image-url: ${IMAGE-URL}

springdoc:
  packages-to-scan: com.jamjam.bookjeok.domains
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8